Enhance/migrate vue3
espressif/vscode-esp-idf-extension pull request #1035
Opened 2023-09-06 11:52 UTC by brianignacio5

## Description

Please include a summary of the change and which issue is fixed.

Fixes #XXX

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "Command"
2. Execute action.
3. Observe results.

- Expected behaviour:

- Expected output:

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- Component 1
- Component 2

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

2023-10-23 11:28 UTC, radurentea requested changes
Left comments for small left overs. Also, the things found by code scanner should be addressed before merging

2023-10-23 11:28 UTC, radurentea commented on src/views/nvs-partition-table/components/Row.vue
> +
Extra empty lines

2023-11-20 12:12 UTC, AndriiFilippov commented
@brianignacio5 hi ! 

```
1. Right click a CMakeLists.txt file and select ESP-IDF: CMakeLists.txt editor command. If the file is root directory choose Project Project CMakeLists.txt otherwise choose Component CMakeLists.txt. Use UI to modify values and see changes on CMakeLists.txt. Run Developer: Open web view Developer tools and see if there is any error in the console.
```

I think we should do some check here, caz it is possible to create multiple configurations for every option:
Not sure if it is OK 

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/94984b0e-3a42-451d-80ed-2f71553884a1)

2023-11-20 13:36 UTC, AndriiFilippov commented
@brianignacio5 

it's tiring to search using scroll, we should definitely have filter for project examples: 

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/32ef3152-f545-4e58-a607-15ff8319f780)

2023-11-20 15:51 UTC, AndriiFilippov commented
@brianignacio5 hi!

1) I think we should add default (namespace) nvs row, like this: 
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/684d1c07-796a-4298-ba5c-1b3571fdf579)

because it is fully empty now.
we have it in IDE:
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/d1f40a97-381b-4a08-b8e9-6193e58d247e)


2) For Type : namespace - lets delete drop-down window because it is empty field(confusing):
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/341c03ca-5260-492f-8006-77e5d3c8bdd5)

2023-11-21 08:49 UTC, kolipakakondal commented
> @brianignacio5 hi! Tested: OS - Windows 10
> 
> Shouldn't this text be active link ? caz when I put cursor on this text - it reacts, but I can't click it
> 
> ![image](https://user-images.githubusercontent.com/69584713/284514941-e83fb25f-3512-4fbb-acef-3cafb08c6cb1.png)

Please show all hyper links text in the blue color
<img width="177" alt="Screenshot 2023-11-21 at 2 19 06 PM" src="https://github.com/espressif/vscode-esp-idf-extension/assets/8463287/401c04e8-f0d3-4a78-8854-2deae742f5c9">

2023-11-21 09:44 UTC, AndriiFilippov commented
Brian, please, explain to me if the "Welcome Page" will be displayed once user install extension from "Extensions" ? 

Because now once I install extension using VSIX -> there is no "Welcome Page" displayed. I should do it manually.

2023-11-21 17:50 UTC, AndriiFilippov commented
@brianignacio5 , hi! 

Should both commands have same structure ? 

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/31406748-9565-4921-bc43-e94b698cc575)

2023-11-22 11:53 UTC, AndriiFilippov commented
@brianignacio5 hi! 

when click "Save" button - there is no info message "Saved successfully" or any other info. I don't understand if it actually saved. 
Can be confusing for user.

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/bf4d2523-0ee4-4f2a-9000-3eba1f0f5796)

2023-11-22 12:17 UTC, AndriiFilippov commented
@brianignacio5, is it possible to add real time validation, caz now it works this way -> validation starts after pressing "Save" button.
So, for example in this case, I have already updated the field with valid value, but it still showing error:
Could be confusing for user.


![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/54135b3b-50eb-4811-a3b4-e0f95d4c3d60)

2023-11-27 17:58 UTC, AndriiFilippov commented
@brianignacio5 hi ! 

Getting some weird notification during 'Extension: Install from VSIX...'
Do you know what could be the reason ? 


![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/2bdc7e66-f306-4c68-ad48-0a2fb7b5a68c)

2023-11-27 18:00 UTC, AndriiFilippov commented
@brianignacio5 

Could we move search a bit left to make it more organic ?
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/4ce7ad5d-f4eb-45bd-b7c6-d18871f83c9a)

2023-11-27 18:20 UTC, AndriiFilippov commented
> @brianignacio5 hi !
> 
> ```
> 1.Right click a CMakeLists.txt file and select ESP-IDF: CMakeLists.txt editor command. If the file is root directory choose Project Project CMakeLists.txt otherwise choose Component CMakeLists.txt. Use UI to modify values and see changes on CMakeLists.txt. Run Developer: Open web view Developer tools and see if there is any error in the console.
> ```
> 
> we should do some check here, caz it is possible to create multiple configurations for every option:
> 
> ![image](https://private-user-images.githubusercontent.com/69584713/284261898-94984b0e-3a42-451d-80ed-2f71553884a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDM4MDcsIm5iZiI6MTcwMTEwMzUwNywicGF0aCI6Ii82OTU4NDcxMy8yODQyNjE4OTgtOTQ5ODRiMGUtM2E0Mi00NTFkLTgwZWQtMmY3MTU1Mzg4NGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2NDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzE4ZDg1ZGM4ODFkNmJjZmNhMmVkMWNmMmQ5MWYyYjViMThiZTk1YjFiODgyM2E4NjhmOGFhMzZmN2Y0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DXg9FFemRNB4WrleaewQiPImai5deaN7PY5A7_wuCtU)

I think we should maybe control this sequence somehow:
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/a6440823-1179-4932-8e6c-5f2958da8a17)

Because I am able to do CMakeList in any sequence:

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/f56453de-b685-4712-bbc1-1798a830b6c1)

2023-11-27 19:14 UTC, AndriiFilippov commented
> @brianignacio5 hi!
> 
> 1. I think we should add default (namespace) nvs row, like this:
>    ![image](https://private-user-images.githubusercontent.com/69584713/284318525-684d1c07-796a-4298-ba5c-1b3571fdf579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTI2MzgsIm5iZiI6MTcwMTExMjMzOCwicGF0aCI6Ii82OTU4NDcxMy8yODQzMTg1MjUtNjg0ZDFjMDctNzk2YS00Mjk4LWJhNWMtMWIzNTcxZmRmNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE5MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0Mjg0OTQ1Nzc2Njg1MzRkYzI5YmFkMTUyNWFjMjQ1MWMxYjdkM2Q5NzVhOGY1MDMyMDhkZjg5NjRhYzRhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KH1Nh775xpO165DiV6mPRCXAW4-vuZp4w8AQMfyG4cI)
> 
> because it is fully empty now. we have it in IDE: ![image](https://private-user-images.githubusercontent.com/69584713/284318827-d1f40a97-381b-4a08-b8e9-6193e58d247e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTI2MzgsIm5iZiI6MTcwMTExMjMzOCwicGF0aCI6Ii82OTU4NDcxMy8yODQzMTg4MjctZDFmNDBhOTctMzgxYi00YTA4LWI4ZTktNjE5M2U1OGQyNDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE5MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTg4NDZjMGE2NjBjNmZjMmRiNjc4NTc3MmRkNDE5ZDllMWZkNjI4MDQyYmJmNmNjYjFmNWVkMzljYjE0YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJOWXB3-UdWE_Ml0v87FW-_CzSQaxfZszRRobbXf5wU)
> 
> 2. For Type : namespace - lets delete drop-down window because it is empty field(confusing):
>    ![image](https://private-user-images.githubusercontent.com/69584713/284319244-341c03ca-5260-492f-8006-77e5d3c8bdd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTI2MzgsIm5iZiI6MTcwMTExMjMzOCwicGF0aCI6Ii82OTU4NDcxMy8yODQzMTkyNDQtMzQxYzAzY2EtNTI2MC00OTJmLTgwMDYtNzdlNWQzYzhiZGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE5MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MWZlMmJlNDU3YjQ4ZTg0MjA5MTM4NmE1ZmY4M2ZhYjIzNGVhMjRmNTQ1OTI3YmVmM2RjODBmMjg4ZTIzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UvrBtp9hLE0d1Ly0lq4MTDNWHx0RLlHyGyStx00g0ZQ)

Still empty

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/36d01a45-bd70-4bba-af37-459ae004610c)

2023-11-28 08:07 UTC, brianignacio5 commented
> @brianignacio5 hi !
> 
> Getting some weird notification during 'Extension: Install from VSIX...' Do you know what could be the reason ?
> 
> ![image](https://private-user-images.githubusercontent.com/69584713/285959528-2bdc7e66-f306-4c68-ad48-0a2fb7b5a68c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTkwMDIsIm5iZiI6MTcwMTE1ODcwMiwicGF0aCI6Ii82OTU4NDcxMy8yODU5NTk1MjgtMmJkYzdlNjYtZjMwNi00YzY4LWFkNDgtMGEyZmI3YjVhNjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA4MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwM2NmMzFmMTQxMjUzM2JhZDEwMGY2ZDRiMGFkNDNjNzdkYTA2Yjg4YmFlMDEzYzkxZTgxNTE1NmNhNThhOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QWMPK0OF31uYPbd74H3jlGro6SL0hdu1-XCKjIVoyMM)

Can you provide the extension log ?

2023-11-28 09:23 UTC, AndriiFilippov commented
> > @brianignacio5 hi !
> > ```
> > 1.Right click a CMakeLists.txt file and select ESP-IDF: CMakeLists.txt editor command. If the file is root directory choose Project Project CMakeLists.txt otherwise choose Component CMakeLists.txt. Use UI to modify values and see changes on CMakeLists.txt. Run Developer: Open web view Developer tools and see if there is any error in the console.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > we should do some check here, caz it is possible to create multiple configurations for every option:
> > ![image](https://private-user-images.githubusercontent.com/69584713/284261898-94984b0e-3a42-451d-80ed-2f71553884a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDM4MDcsIm5iZiI6MTcwMTEwMzUwNywicGF0aCI6Ii82OTU4NDcxMy8yODQyNjE4OTgtOTQ5ODRiMGUtM2E0Mi00NTFkLTgwZWQtMmY3MTU1Mzg4NGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2NDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzE4ZDg1ZGM4ODFkNmJjZmNhMmVkMWNmMmQ5MWYyYjViMThiZTk1YjFiODgyM2E4NjhmOGFhMzZmN2Y0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DXg9FFemRNB4WrleaewQiPImai5deaN7PY5A7_wuCtU)
> 
> I think we should maybe control this sequence somehow: ![image](https://private-user-images.githubusercontent.com/69584713/285968645-a6440823-1179-4932-8e6c-5f2958da8a17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjE3NTUsIm5iZiI6MTcwMTE2MTQ1NSwicGF0aCI6Ii82OTU4NDcxMy8yODU5Njg2NDUtYTY0NDA4MjMtMTE3OS00OTMyLThlNmMtNWYyOTU4ZGE4YTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA4NTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MDYxYTA3NTQ2Zjg2NGNkOTE0ODVhY2I3NDM1ZjA0ZDNiNDMwM2M3MWM0MTM4ZmVkMjViOWM4MWVmZjFlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vf9VPzqc6e9Ylb9xR6NUQQmv6v_K13hdrATHBBL9e0g)
> 
> Because I am able to do CMakeList in any sequence:
> 
> ![image](https://private-user-images.githubusercontent.com/69584713/285969276-f56453de-b685-4712-bbc1-1798a830b6c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjE3NTUsIm5iZiI6MTcwMTE2MTQ1NSwicGF0aCI6Ii82OTU4NDcxMy8yODU5NjkyNzYtZjU2NDUzZGUtYjY4NS00NzEyLWJiYzEtMTc5OGE4MzBiNmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA4NTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTRkNGJhZDQ4MzliMmM5OTQzY2MzOGRmZjVjNDM5NjRlNzM3MTMzMWUzYmE4MzNjNTIxYjUxYThkMGYyNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNdPYmjl9I3R2OcKF879L6s5wr1xwwtg5_6WmJu6rrc)

@brianignacio5 hi ! 

I forgot to add link. 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#mandatory-parts

The optional variables: 
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/879f779a-b177-400a-b7d8-edad846bec49)

I do see structure in CMake editor: 
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/87ba3bee-b6f0-496a-b0c1-09f9cb805273)

but once I open CMakeList.txt I do see the disordered structure: 

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/bfc54326-537e-44f6-b071-69c09f5394f9)

2023-11-28 12:35 UTC, AndriiFilippov commented
@brianignacio5 

open CMakeList.txt -> delete everything, only Project Name and Minimum Required 
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/e23114c1-fb88-4809-a076-2b8f1aa7d3f2)

add 'Set variable with value set (VARIABLE "VALUE")  -> fill and save -> it disappears from CMake Editor but could see it in CMakeList.txt ->

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/e6c44153-bda6-427d-98c7-568940a2e05e)
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/7f643b6b-c493-438c-ae71-03bea6c61d53)

2023-11-28 12:42 UTC, AndriiFilippov commented
@brianignacio5 

open CMakeList.txt -> delete everything, only Project Name and Minimum Required

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/abbaf80b-cb3e-4aee-b9e5-b065d6e8f067)

add Include PATH first -> next add  'Set variable with value set (VARIABLE "VALUE") like this ->

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/8319083f-0e15-4621-8bfc-98fbc37164c2)

save -> open CMakeList -> wrong sequence ->

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/fd32ae93-6a9a-4d72-a733-468b5abfe2aa)

2023-11-30 14:10 UTC, AndriiFilippov commented
@brianignacio5 , please, add message during tool installation via Espressif server, as we discussed before.

2023-12-19 15:19 UTC, AndriiFilippov commented
@brianignacio5 hi ! 

tick on "Show Welcome on extension startup" does not work. ESP Welcome windows appears on every VS Code start. 
This is good advertising for us, but I’m afraid it will annoy users 🤪 

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/85976c17-0215-42da-a9ba-dd9621dc4cbd)

2023-12-19 15:28 UTC, AndriiFilippov commented
@brianignacio5 

Windows 10 
ESP-IDF: v5.1.1 

after project creation -> build -> error 

`
[0/1] Re-running CMake...
-- ccache will be used for faster recompilation
-- Building ESP-IDF components for target esp32
CMake Error at C:/Users/AndriiFilippov/e/esp-idf-v5.1.1/tools/cmake/build.cmake:540 (message):
Call Stack (most recent call first):
  C:/Users/AndriiFilippov/e/esp-idf-v5.1.1/tools/cmake/project.cmake:547 (idf_build_process)
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/AndriiFilippov/e/esp-idf-v5.1.1/examples/get-started/hello_world/build/CMakeFiles/CMakeOutput.log".
←[31mFAILED: ←[0mbuild.ninja
C:\Users\AndriiFilippov\.espressif\tools\cmake\3.24.0\bin\cmake.exe --regenerate-during-build -SC:\Users\AndriiFilippov\e\esp-idf-v5.1.1\examples\get-started\hello_world -BC:\Users\AndriiFilippov\e\esp-idf-v5.1.1\examples\get-started\hello_world\build
ninja: error: rebuilding 'build.ninja': subcommand failed

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja " terminated with exit code: 1. 
`

2023-12-19 15:44 UTC, AndriiFilippov commented
> @brianignacio5
> 
> open CMakeList.txt -> delete everything, only Project Name and Minimum Required ![image](https://private-user-images.githubusercontent.com/69584713/286250787-e23114c1-fb88-4809-a076-2b8f1aa7d3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTA3ODctZTIzMTE0YzEtZmI4OC00ODA5LWEwNzYtMmI4ZjFhYTdkM2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzZkODk2ZTNmM2I1NmU2ZWIwYmYwNmEwYmVjYjUzMTYwN2Q5Y2RkOTAyZWUzZjhkYTc2ZTI5NTU1MzMyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JLu3pgulncXmfNKk6hLzJe6cu2h7Enj8N3tO6sDcDp0)
> 
> add 'Set variable with value set (VARIABLE "VALUE") -> fill and save -> it disappears from CMake Editor but could see it in CMakeList.txt ->
> 
> ![image](https://private-user-images.githubusercontent.com/69584713/286251106-e6c44153-bda6-427d-98c7-568940a2e05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExMDYtZTZjNDQxNTMtYmRhNi00MjdkLTk4YzctNTY4OTQwYTJlMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWRhNzBiYzM4ZTY4ZWI2ODcxYjViZDY4NjBiYmEzZTMxYjM2MmVjNDY3ZjlhMjI1NWM0YTM1M2IxM2FhNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0npy_z2iOzcZlONUs867k1NYlPgW5sdL13wj4UGYLcs) ![image](https://private-user-images.githubusercontent.com/69584713/286251151-7f643b6b-c493-438c-ae71-03bea6c61d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExNTEtN2Y2NDNiNmItYzQ5My00MzhjLWFlNzEtMDNiZWE2YzYxZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGRmMWNiZDQ4NmFlMzUyMjgxYzU1MjA4ZDA1ZGQ3NjRmOWZiNGJlMTZhMDNkYzlkNDNlNDBkNjExMGZmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ybYtDzwcLAxgZ5R5gnPbitmdT-Vp8HjIGw26ad7J93I)

still persist. 
Open CMake editor -> add 'Set variable with value' -> fin and save -> disappears from editor.

2023-12-19 15:56 UTC, AndriiFilippov commented
@brianignacio5 

able to save CMake editor with Mandatory Parts such as Project Name or Minimum Requirement deleted.  

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/6051cba4-ba9c-43b1-8e6b-85e83ff51d7e)

2023-12-20 01:09 UTC, brianignacio5 commented
> > @brianignacio5
> > open CMakeList.txt -> delete everything, only Project Name and Minimum Required ![image](https://private-user-images.githubusercontent.com/69584713/286250787-e23114c1-fb88-4809-a076-2b8f1aa7d3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTA3ODctZTIzMTE0YzEtZmI4OC00ODA5LWEwNzYtMmI4ZjFhYTdkM2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzZkODk2ZTNmM2I1NmU2ZWIwYmYwNmEwYmVjYjUzMTYwN2Q5Y2RkOTAyZWUzZjhkYTc2ZTI5NTU1MzMyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JLu3pgulncXmfNKk6hLzJe6cu2h7Enj8N3tO6sDcDp0)
> > add 'Set variable with value set (VARIABLE "VALUE") -> fill and save -> it disappears from CMake Editor but could see it in CMakeList.txt ->
> > ![image](https://private-user-images.githubusercontent.com/69584713/286251106-e6c44153-bda6-427d-98c7-568940a2e05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExMDYtZTZjNDQxNTMtYmRhNi00MjdkLTk4YzctNTY4OTQwYTJlMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWRhNzBiYzM4ZTY4ZWI2ODcxYjViZDY4NjBiYmEzZTMxYjM2MmVjNDY3ZjlhMjI1NWM0YTM1M2IxM2FhNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0npy_z2iOzcZlONUs867k1NYlPgW5sdL13wj4UGYLcs) ![image](https://private-user-images.githubusercontent.com/69584713/286251151-7f643b6b-c493-438c-ae71-03bea6c61d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExNTEtN2Y2NDNiNmItYzQ5My00MzhjLWFlNzEtMDNiZWE2YzYxZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGRmMWNiZDQ4NmFlMzUyMjgxYzU1MjA4ZDA1ZGQ3NjRmOWZiNGJlMTZhMDNkYzlkNDNlNDBkNjExMGZmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ybYtDzwcLAxgZ5R5gnPbitmdT-Vp8HjIGw26ad7J93I)
> 
> still persist. Open CMake editor -> add 'Set variable with value' -> fin and save -> disappears from editor.

What is `fin and save` ?

2024-01-08 15:21 UTC, AndriiFilippov commented
> > @brianignacio5
> > open CMakeList.txt -> delete everything, only Project Name and Minimum Required ![image](https://private-user-images.githubusercontent.com/69584713/286250787-e23114c1-fb88-4809-a076-2b8f1aa7d3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTA3ODctZTIzMTE0YzEtZmI4OC00ODA5LWEwNzYtMmI4ZjFhYTdkM2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzZkODk2ZTNmM2I1NmU2ZWIwYmYwNmEwYmVjYjUzMTYwN2Q5Y2RkOTAyZWUzZjhkYTc2ZTI5NTU1MzMyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JLu3pgulncXmfNKk6hLzJe6cu2h7Enj8N3tO6sDcDp0)
> > add 'Set variable with value set (VARIABLE "VALUE") -> fill and save -> it disappears from CMake Editor but could see it in CMakeList.txt ->
> > ![image](https://private-user-images.githubusercontent.com/69584713/286251106-e6c44153-bda6-427d-98c7-568940a2e05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExMDYtZTZjNDQxNTMtYmRhNi00MjdkLTk4YzctNTY4OTQwYTJlMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWRhNzBiYzM4ZTY4ZWI2ODcxYjViZDY4NjBiYmEzZTMxYjM2MmVjNDY3ZjlhMjI1NWM0YTM1M2IxM2FhNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0npy_z2iOzcZlONUs867k1NYlPgW5sdL13wj4UGYLcs) ![image](https://private-user-images.githubusercontent.com/69584713/286251151-7f643b6b-c493-438c-ae71-03bea6c61d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExNTEtN2Y2NDNiNmItYzQ5My00MzhjLWFlNzEtMDNiZWE2YzYxZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGRmMWNiZDQ4NmFlMzUyMjgxYzU1MjA4ZDA1ZGQ3NjRmOWZiNGJlMTZhMDNkYzlkNDNlNDBkNjExMGZmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ybYtDzwcLAxgZ5R5gnPbitmdT-Vp8HjIGw26ad7J93I)
> 
> still persist. Open CMake editor -> add 'Set variable with value' -> fill and save -> disappears from editor.

issue still persist.

2024-01-09 09:48 UTC, brianignacio5 commented
> > > @brianignacio5
> > > open CMakeList.txt -> delete everything, only Project Name and Minimum Required ![image](https://private-user-images.githubusercontent.com/69584713/286250787-e23114c1-fb88-4809-a076-2b8f1aa7d3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTA3ODctZTIzMTE0YzEtZmI4OC00ODA5LWEwNzYtMmI4ZjFhYTdkM2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzZkODk2ZTNmM2I1NmU2ZWIwYmYwNmEwYmVjYjUzMTYwN2Q5Y2RkOTAyZWUzZjhkYTc2ZTI5NTU1MzMyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JLu3pgulncXmfNKk6hLzJe6cu2h7Enj8N3tO6sDcDp0)
> > > add 'Set variable with value set (VARIABLE "VALUE") -> fill and save -> it disappears from CMake Editor but could see it in CMakeList.txt ->
> > > ![image](https://private-user-images.githubusercontent.com/69584713/286251106-e6c44153-bda6-427d-98c7-568940a2e05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExMDYtZTZjNDQxNTMtYmRhNi00MjdkLTk4YzctNTY4OTQwYTJlMDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWRhNzBiYzM4ZTY4ZWI2ODcxYjViZDY4NjBiYmEzZTMxYjM2MmVjNDY3ZjlhMjI1NWM0YTM1M2IxM2FhNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0npy_z2iOzcZlONUs867k1NYlPgW5sdL13wj4UGYLcs) ![image](https://private-user-images.githubusercontent.com/69584713/286251151-7f643b6b-c493-438c-ae71-03bea6c61d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDA2MjgsIm5iZiI6MTcwMzAwMDMyOCwicGF0aCI6Ii82OTU4NDcxMy8yODYyNTExNTEtN2Y2NDNiNmItYzQ5My00MzhjLWFlNzEtMDNiZWE2YzYxZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE1Mzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGRmMWNiZDQ4NmFlMzUyMjgxYzU1MjA4ZDA1ZGQ3NjRmOWZiNGJlMTZhMDNkYzlkNDNlNDBkNjExMGZmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ybYtDzwcLAxgZ5R5gnPbitmdT-Vp8HjIGw26ad7J93I)
> > 
> > 
> > still persist. Open CMake editor -> add 'Set variable with value' -> fill and save -> disappears from editor.
> 
> issue still persist.

Should be fixed with latest commit.

2024-01-09 13:59 UTC, AndriiFilippov commented
> @brianignacio5 , hi!
> 
> Should both commands have same structure ?
> 
> ![image](https://private-user-images.githubusercontent.com/69584713/284671674-31406748-9565-4921-bc43-e94b698cc575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDQ4MjYsIm5iZiI6MTcwNDgwNDUyNiwicGF0aCI6Ii82OTU4NDcxMy8yODQ2NzE2NzQtMzE0MDY3NDgtOTU2NS00OTIxLWJjNDMtZTk0YjY5OGNjNTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEyNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMTMzOTNhZDI4OTk5YTQ1MmQyYThmYmZkMmNjNWE0ZjVkMzgxMTI0MzljZjVkNWNlOWUxYTc2MmNhNzQ1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VqByE7hQkWx3ztRGvovrcHzXV0Du_WsB35xzd3wjx-U)

Please, fix this one

2024-01-09 13:59 UTC, AndriiFilippov commented
> @brianignacio5 hi!
> 
> when click "Save" button - there is no info message "Saved successfully" or any other info. I don't understand if it actually saved. Can be confusing for user.
> 
> ![image](https://private-user-images.githubusercontent.com/69584713/284894182-bf4d2523-0ee4-4f2a-9000-3eba1f0f5796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDQ4MjYsIm5iZiI6MTcwNDgwNDUyNiwicGF0aCI6Ii82OTU4NDcxMy8yODQ4OTQxODItYmY0ZDI1MjMtMGVlNC00ZjJhLTkwMDAtM2ViYTFmMGY1Nzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEyNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZGYzODI4MjU4NGU3N2NiZTcxZGJjODlmZTc4M2I1MGMwNDQxYjAyNmUzMWY3MjNiYTFiZmE2N2ExNDQzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kq60QxnFjQjYgRxkuAI_jDLGWdmmOHvz2To5vi2zbm8)

Please, fix this one

2024-01-09 14:05 UTC, AndriiFilippov commented
@brianignacio5 hi ! 

Could you please explain to me the meaning of "Retry" button ? 

![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/5a6f1af5-241d-4958-9760-b439c7ec9ad5)

2024-01-09 14:07 UTC, brianignacio5 commented
> > @brianignacio5 hi!
> > when click "Save" button - there is no info message "Saved successfully" or any other info. I don't understand if it actually saved. Can be confusing for user.
> > ![image](https://private-user-images.githubusercontent.com/69584713/284894182-bf4d2523-0ee4-4f2a-9000-3eba1f0f5796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDQ4MjYsIm5iZiI6MTcwNDgwNDUyNiwicGF0aCI6Ii82OTU4NDcxMy8yODQ4OTQxODItYmY0ZDI1MjMtMGVlNC00ZjJhLTkwMDAtM2ViYTFmMGY1Nzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEyNDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZGYzODI4MjU4NGU3N2NiZTcxZGJjODlmZTc4M2I1MGMwNDQxYjAyNmUzMWY3MjNiYTFiZmE2N2ExNDQzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kq60QxnFjQjYgRxkuAI_jDLGWdmmOHvz2To5vi2zbm8)
> 
> Please, fix this one

This will fix in another PR. Not related to changes in this PR (purely UI )



> @brianignacio5 hi !
> 
> Could you please explain to me the meaning of "Retry" button ?
> 
> ![image](https://private-user-images.githubusercontent.com/69584713/295229341-5a6f1af5-241d-4958-9760-b439c7ec9ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDk0MjAsIm5iZiI6MTcwNDgwOTEyMCwicGF0aCI6Ii82OTU4NDcxMy8yOTUyMjkzNDEtNWE2ZjFhZjUtMjQxZC00OTU4LTk3NjAtYjQzOWM3ZWM5YWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMWM3ZmI3YzcyZmQ2Y2VhMzY5M2RjZjFlOWRiZTcxMGU1YmQ1Zjk0NGY3ZGFmMTk2ZjYxMGM4YmUzNDljY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2L8S2pjacENG14e-q9osY-ocqXu1gEmusoHULtFmGkk)

This is to reload the partition table content from the CSV (kinda like a reset button)

2024-01-16 10:49 UTC, AndriiFilippov commented
@brianignacio5 hi ! 

Tested under: 
OS - Windows 10 
ESP-IDF:  v5.1.2 

LGTM 👍

2024-01-19 07:11 UTC, merged