update dockerfile and qemu options
espressif/vscode-esp-idf-extension pull request #1282
Opened 2024-08-16 10:31 UTC by brianignacio5

## Description

Update Dockerfile and QEMU options.:

- Remove adding QEMU in Dockerfile and using the one from ESP-IDF tools. 
- Adding QEMU options to support both esp32 and esp32c3 as target.
- Add `${idf.buildPath}/merged-qemu.bin` delete when `${idf.buildPath}/.bin_timestamp` changes to trigger rebuilding the merged QEMU bin image.

Fixes #1281

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "ESP-IDF: Launch QEMU Debug Session" or `ESP-IDF: Monitor QEMU Device` should work for esp32 or esp32c3 and show error for other IDF_TARGET. 
2. Change the source code. The `merged-qemu.bin` should be deleted.
4. Click on "ESP-IDF: Launch QEMU Debug Session" or `ESP-IDF: Monitor QEMU Device` and the new image should be generated and used.

- Expected behaviour:

- Expected output:

## How has this been tested?

Manual testing in a Dev Container in Visual Studio Code running previous code on ESP-IDF project like the blink example.

**Test Configuration**: Using VSCode Devcontainer Docker container in either Windows or MacOS
* ESP-IDF Version: 5.4
* OS (Windows,Linux and macOS): macOS

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

2024-10-14 10:47 UTC, brianignacio5 commented
PTAL @radurentea  @Fabricio-ESP

2024-10-21 14:37 UTC, radurentea requested changes
Left some comments related to some small text changes

2024-10-21 15:41 UTC, radurentea commented
Hi @brianignacio5,

I've left some small comments related to consistency of the text and translations.

Also, when testing I ran into the following issues:

1. Docker container does not come pre-configured as stated in our [documentation](https://docs.espressif.com/projects/vscode-esp-idf-extension/en/latest/additionalfeatures/qemu.html) at step 4, python path is missing, which causes issues with the commands that are using python (ex: setting device target etc)
2. When trying to configure the extension inside the docker container, python path still doesn't changes.

2024-10-22 00:53 UTC, brianignacio5 commented
> Hi @brianignacio5,
> 
> I've left some small comments related to consistency of the text and translations.
> 
> Also, when testing I ran into the following issues:
> 
> 1. Docker container does not come pre-configured as stated in our [documentation](https://docs.espressif.com/projects/vscode-esp-idf-extension/en/latest/additionalfeatures/qemu.html) at step 4, python path is missing, which causes issues with the commands that are using python (ex: setting device target etc)
> 2. When trying to configure the extension inside the docker container, python path still doesn't changes.

2 things you need to consider:

1. Are you re opening a ESP-IDF project that already has .vscode/settings.json into a Docker Container ? Do you have python path defined there? The container will use settings from `.devcontainer/devcontainer.json` IF .vscode/settings.json are not defined.
2. When you re-open a project in a Docker container, the extension installed is from marketplace. Have you reinstalled the vsix from this PR in the container to see if it works. The python path issue is from marketplace extension which should be resolved with the removal of python path settings. 
3. A doctor command output  from the container will show you what settings are used in the container. If you see python path. Please share this doctor command output.

2024-10-22 10:06 UTC, radurentea commented
Hi @brianignacio5,

1. I've checked and indeed the settings.json inside the project was configured with the settings from my Mac. I thought the Remote Settings will have higher priority, but it was not the case
2. I did not think of that, but it makes sense that I had to install a new version of the extension.

After properly configuring the container settings, the issue has been resolved.

The project is now working as expected. I'll create a separate ticket to investigate a more robust solution for managing configuration switches between local development and container environments as we've discussed.

2024-10-25 07:45 UTC, radurentea approved these changes
LGTM!

2024-10-28 00:11 UTC, merged