Fix duplicate output; Add notification for success
espressif/vscode-esp-idf-extension pull request #1290
Opened 2024-08-26 13:10 UTC by radurentea

## Description

Removed duplicated output to ESP-IDF channel, when user sets device target (ex: esp32, esp32s2 etc)
Added notification for successfully setting the target
Improved error message

JIRA: https://jira.espressif.com:8443/browse/VSC-1430

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

1) Open a project
2) Set any device target
3) Check "ESP-IDF" Output channel. There should be no duplicates of `Executing "cmake`
4) When setting the device is finished, you should get a notification no matter if it's successful or not.

## How has this been tested?

As described above

**Test Configuration**:
* ESP-IDF Version: 5.2.2
* OS (Windows,Linux and macOS): Windows 11

## Checklist
- [ ] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

2024-08-26 14:45 UTC, radurentea commented
Hi @brianignacio5, PTAL

2024-08-27 07:48 UTC, brianignacio5 requested changes
Can still see the same message being output in 2 places.

Suggest further reduce code duplication here.

2024-08-27 07:48 UTC, brianignacio5 commented on src/espIdf/setTarget/index.ts
> +          const msg = l10n.t(
This message and the output is still duplicate from `src/espIdf/setTarget/setTargetInIdf`. 

I suggest simplify this further, seems both codes could benefit for a single implementation

2024-09-10 09:42 UTC, brianignacio5 approved these changes
LGTM

2024-09-10 09:45 UTC, radurentea commented
Hi @Fabricio-ESP , PTAL

2024-10-24 04:09 UTC, brianignacio5 approved these changes
LGTM

2024-10-24 11:14 UTC, Fabricio-ESP approved these changes
Tested on windows, Linux ubuntu and on WSL ubuntu.
Cmake only run once no issues found on normal operation of the extension.

2024-10-25 07:03 UTC, merged