rm old docs update links
espressif/vscode-esp-idf-extension pull request #1342
Opened 2024-11-13 08:39 UTC by brianignacio5

## Description

* Remove GitHub documentation in favor of Espressif documentation.
* Update documentation links in README.md
* Add basic setup for `zh_CN` language build and update CI to include both.

## Type of change

- This change requires a documentation update

## Steps to test this pull request

Open Preview documentation link in this PR. Review documentation in Chinese.

Test readme links and extension links are updated.

## How has this been tested?

Test by click links in read and extension links. Check preview documentation that zh_CN is generated.

**Test Configuration**:
* ESP-IDF Version: Not relevant
* OS (Windows,Linux and macOS): Not related

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

2024-11-14 03:03 UTC, Shen765 approved these changes

2024-11-18 09:25 UTC, radurentea approved these changes
LGTM

2024-11-18 10:52 UTC, Fabricio-ESP requested changes
All good besides the broken code of conduct link.

2024-11-18 10:52 UTC, Fabricio-ESP commented on README.md
> +This project and everyone participating in it is governed by the [Code of Conduct](./CODE_OF_CONDUCT.md). By participating, you are expected to uphold this code. Please report unacceptable behavior t
Make sure to move the CODE_OF_CONDUCT file to correct location, I don't see it in the git diff.

2024-11-18 10:58 UTC, Fabricio-ESP commented
@brianignacio5 
Additional to your changes, There are some broken links in the "All Available commands" table, making references to files deleted in this PR. PTAL

2024-11-18 11:49 UTC, Fabricio-ESP commented on README.md
> +This project and everyone participating in it is governed by the [Code of Conduct](./CODE_OF_CONDUCT.md). By participating, you are expected to uphold this code. Please report unacceptable behavior t
Fixed on commit: [b6f1eff](https://github.com/espressif/vscode-esp-idf-extension/pull/1342/commits/b6f1effc9bb4f160fbd2f56aec7032b88ca8828b)

2024-11-18 11:51 UTC, Fabricio-ESP approved these changes
All looks good now.

2024-11-19 00:46 UTC, merged