Simplify onboarding
espressif/vscode-esp-idf-extension pull request #159
Opened 2020-09-01 14:11 UTC by brianignacio5

This branch is built to simplify user setup window.

2020-09-17 07:16 UTC, pwmb requested changes
If I select the folder with IDF already there and try to install latest version of idf its going to this next page and UI freezes, ideally if folder had IDF already IDF, show the warning to user that this will override any changes they have there, and they can press `Yes` or `Continue` to proceed 

![Screen Shot 2020-09-17 at 12 38 47 PM](https://user-images.githubusercontent.com/25585652/93432141-bcad6900-f8e2-11ea-9150-a2d82a0de85f.png)

---

`Use existing ESP-IDF setup` button is non functional!!

---

Old error is persisting, even after changing the directory (should be reactive)

![Screen Shot 2020-09-17 at 12 42 43 PM](https://user-images.githubusercontent.com/25585652/93432523-49f0bd80-f8e3-11ea-97d3-234a67f5fa2b.png)

Same here

![Screen Shot 2020-09-17 at 12 44 38 PM](https://user-images.githubusercontent.com/25585652/93432731-8e7c5900-f8e3-11ea-8669-a17eeba9e024.png)

2020-09-17 09:23 UTC, brianignacio5 commented
Hmm should redirected to install page if error happens. Will fix.

> `Use existing ESP-IDF setup` button is non functional!!

Any error in the logs or vscode Developer Tools console ?

2020-09-29 01:28 UTC, brianignacio5 commented
> 
> 
> If I select the folder with IDF already there and try to install latest version of idf its going to this next page and UI freezes, ideally if folder had IDF already IDF, show the warning to user that this will override any changes they have there, and they can press `Yes` or `Continue` to proceed
> 
> ![Screen Shot 2020-09-17 at 12 38 47 PM](https://user-images.githubusercontent.com/25585652/93432141-bcad6900-f8e2-11ea-9150-a2d82a0de85f.png)
> 
> `Use existing ESP-IDF setup` button is non functional!!
> 
> Old error is persisting, even after changing the directory (should be reactive)
> 
> ![Screen Shot 2020-09-17 at 12 42 43 PM](https://user-images.githubusercontent.com/25585652/93432523-49f0bd80-f8e3-11ea-97d3-234a67f5fa2b.png)
> 
> Same here
> 
> ![Screen Shot 2020-09-17 at 12 44 38 PM](https://user-images.githubusercontent.com/25585652/93432731-8e7c5900-f8e3-11ea-8669-a17eeba9e024.png)

This should be fixed. Please check the other errors.

2020-10-14 06:38 UTC, pwmb requested changes

2020-10-14 06:38 UTC, pwmb commented on src/views/setup/Home.vue
> +        <a href="https://git-scm.com/downloads">Git</a>
Link on hover is not readable

2020-10-14 06:38 UTC, pwmb commented on src/views/setup/Home.vue
> +        <a href="https://git-scm.com/downloads">Git</a>
I am getting no buttons to proceed or take action

![Screen Shot 2020-10-14 at 12 07 43 PM](https://user-images.githubusercontent.com/25585652/95952513-e3918900-0e15-11eb-8464-2a44e113b960.png)

2020-10-14 12:57 UTC, pwmb requested changes
CSS Suggestions

- Add a box/border around so that these options just don't like text
- On mouse Hover on them change cursor to pointer to indicate link
- Also on hover change the text to blue (which is already the current behavior)

![Screen Shot 2020-10-14 at 6 17 49 PM](https://user-images.githubusercontent.com/25585652/95990897-b6f76480-0e49-11eb-87d8-3a45980336ba.png)

- Left align the content in card (not center) and Right align the action buttons

![Screen Shot 2020-10-14 at 6 23 10 PM](https://user-images.githubusercontent.com/25585652/95991685-b6130280-0e4a-11eb-8298-685f4ee03d14.png)


- First screen for both `Express` & `Advance` are identical is this intensional ?

2020-10-15 12:15 UTC, brianignacio5 commented
CSS suggestions should have been fixed.

> First screen for both Express & Advance are identical is this intensional ?

Yes because it is necessary for both advanced and express setup modes. Tools need ESP-IDF to be defined first in any case.

2020-10-20 16:11 UTC, pwmb requested changes
- `CSS`: On hover drop-down icon color needs to be updated
![Screen Shot 2020-10-20 at 9 30 11 PM](https://user-images.githubusercontent.com/25585652/96613145-3ab6c280-131c-11eb-9f85-32341bd8cf7c.png)

- `CSS`: Those spinner icon are not spinning, also for ESP-IDF we have percentage then I think its better to show percentage and no spinner.

![Screen Shot 2020-10-20 at 9 33 29 PM](https://user-images.githubusercontent.com/25585652/96613271-5f129f00-131c-11eb-8a2b-36dc8195356a.png)

- `CSS`: Error message is too in the way, also can't be canceled.

![Screen Shot 2020-10-20 at 9 34 31 PM](https://user-images.githubusercontent.com/25585652/96613399-8b2e2000-131c-11eb-84de-e47690a42202.png)

- `Behaviour`: User should not be allowed to go to home or navigate away while download is happening, because it creates a race condition. (simple button disable should be fine)

![Screen Shot 2020-10-20 at 9 34 04 PM](https://user-images.githubusercontent.com/25585652/96613608-c892ad80-131c-11eb-97c9-80961e136a3e.png)


- `Question`: How user can set already downloaded IDF path, its should be part of advance mode I think?

2020-10-21 09:55 UTC, brianignacio5 commented
> Question: How user can set already downloaded IDF path, its should be part of advance mode I think?

In `Select ESP-IDF` dropdown options, there is an option to `Find ESP-IDF in your system`.

2020-10-26 10:18 UTC, pwmb approved these changes
LGTM

2020-11-16 14:49 UTC, kumekay commented
I like the new download screen, it concise and informative. Great improvement.

My exprerience with the installer. Here are issues I encoutered on Windows 10 20h2 in WSL2 with ubuntu 20.04

What is the difference between advanced and express installation? Both of them lead to configuration page. 
![image](https://user-images.githubusercontent.com/2738/99266219-d4419900-2822-11eb-970c-eae2f8bcef5d.png)

Switching animation between screens is too long. It feels unresponsive. 0.4 s will be enough.

Missing space for label:
![image](https://user-images.githubusercontent.com/2738/99244827-eb708e80-2802-11eb-99d6-0c1e8ad591a1.png)

May the install create full path automatically, if it doesn't exist? Error messages doesn't fit.
![image](https://user-images.githubusercontent.com/2738/99264825-40bb9880-2821-11eb-8d2a-261082850c65.png)

The error is still on the next step, even after I created the path manually and installation goes normally:
![image](https://user-images.githubusercontent.com/2738/99265210-ba538680-2821-11eb-9639-e29bccb39bb4.png)

I randomly receive 
![image](https://user-images.githubusercontent.com/2738/99265600-2930df80-2822-11eb-8a52-f6b689042d93.png)

Log doesn't contain anything useful:

```
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.79% (83343.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.81% (83359.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.83% (83375.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.85% (83391.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.87% (83407.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.89% (83423.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.91% (83439.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.93% (83455.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.95% (83471.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.97% (83487.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 99.99% (83503.63 / 83515.85) KB
xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz progress: 100.00% (83515.85 / 83515.85) KB
```
Another issue that download progress is too verbose.

On download page progress bar for xtensa-esp32-elf  is filled with pervious attempt results. 
![image](https://user-images.githubusercontent.com/2738/99266384-fd622980-2822-11eb-9d9f-852a3145fcfe.png)

Wrong `\` slash for WSL path
![image](https://user-images.githubusercontent.com/2738/99245065-499d7180-2803-11eb-91dc-902334a95616.png)

2020-11-16 14:56 UTC, kumekay commented
On Windows directly, install button doesn't work. Screenshot with error is attached:

![image](https://user-images.githubusercontent.com/2738/99267459-41096300-2824-11eb-966a-62108becb239.png)

2020-12-01 10:08 UTC, brianignacio5 commented
> What is the difference between advanced and express installation? Both of them lead to configuration page.

Advanced allows you to modify Tools directory folder or enter each tool path manually.

> With the second attempt it logged the error. Is codespace somehow hardcoded?

No it is not. `/home/codespace` is obtained from $HOME, the default tools directory is `$HOME/.espressif`.

Fixed other issues mentioned by @kumekay Please take a look again when possible.

2021-01-04 08:53 UTC, pwmb approved these changes

2021-01-04 11:08 UTC, merged