JTAG Flash Support
espressif/vscode-esp-idf-extension pull request #183
Opened 2020-09-29 12:29 UTC by pwmb

This feature will enable to flash device via JTAG

> Awaits the release from `open-ocd`

2020-11-26 09:19 UTC, pwmb commented
> Note: Must have OpenOCD version [v0.10.0-esp32-20201125](https://github.com/espressif/openocd-esp32/releases/tag/v0.10.0-esp32-20201125) or later

2020-11-27 05:47 UTC, newblaque approved these changes

2020-11-27 05:47 UTC, newblaque approved these changes

2020-11-30 10:32 UTC, brianignacio5 requested changes
Tested on MacOS.  Feature looks really well and working properly.

Left some comments otherwise LGTM.

2020-11-30 10:32 UTC, brianignacio5 commented on src/extension.ts
> +      if (!existsSync(buildFolder)) {
We should also check `.elf` is generated, build folder is still created on build failure.

2020-11-30 10:32 UTC, brianignacio5 commented on package.json
> +        "title": "Select Flash Device and Flash",
Add Localization for `Select Flash Method` ? 

Should also rename old  flash method to Flash (UART)

2020-11-30 10:32 UTC, brianignacio5 commented on src/extension.ts
> +      if (!existsSync(buildFolder)) {
Wouldn't be better to use `pathExists` from path-extra for async instead of fs `existsSync` ?

2020-12-02 04:54 UTC, brianignacio5 approved these changes
LGTM

2020-12-28 10:32 UTC, merged