Tutorials docs
espressif/vscode-esp-idf-extension pull request #332
Opened 2021-02-26 04:28 UTC by brianignacio5

Adding tutorial documentation for the extension. 

- [ ] Extension Setup
- [ ] SDK Configuration editor, Build, Flash, monitor tutorial with blink_example
- [ ] Debugging with blink_example
- [ ] Code coverage
- [ ] Partition table editor
- [ ] NVS Partition editor
- [ ] System view tracing
- [ ] CMakeLists.txt editor

2021-03-11 13:07 UTC, brianignacio5 commented on docs/COVERAGE.md
> +This extension requires `gcovr` to generate JSON and HTML reports from generated files. This is installed as part of this extension ESP-IDF Debug Adapter Python requirements when following the **ESP-
It is old information that needs to be updated, was removed from debug adapter and moved to extension requirements.txt. Will make updates as suggested !

2021-03-11 13:21 UTC, brianignacio5 commented on docs/SETUP.md
> +You also need to install extension and debug adapter python packages requirements.txt.
The thing is, if the user wants to manually set the extension, both JSON and UI Manual configuration will not install extension and debug adapter requirements.txt, so I think they need to be reminded to install them in their python virtual environment. Not sure about where will be good to add this text though.

2021-03-16 04:13 UTC, krzychb requested changes
@brianignacio5 please see some comments.

2021-03-17 05:52 UTC, brianignacio5 commented on docs/tutorial/debugging.md
> +# Watching and setting program variables
Currently is not part of vscode debug features. Reference : [vscode issue](https://github.com/microsoft/vscode/issues/105406)

2021-03-17 06:13 UTC, brianignacio5 commented on docs/tutorial/debugging.md
> +
not implemented yet in the debug adapter.

2021-03-22 08:09 UTC, brianignacio5 commented on docs/tutorial/debugging.md
> +
Yes, I had add it in the debug tutorial, I wasn't sure at first but did tested and it works.

2021-04-06 03:28 UTC, brianignacio5 commented
@krzychb @gerekon Can we close this ? Or do you think there is something we could improve/add ?

2021-04-06 05:53 UTC, krzychb commented
> @krzychb @gerekon Can we close this ? Or do you think there is something we could improve/add ?

LGTM

2021-04-08 03:37 UTC, merged