Log Doctor Command; Replace path with '...'
espressif/vscode-esp-idf-extension pull request #805
Opened 2022-09-20 11:31 UTC by radurentea

## Description
* Add Doctor Command's output to Log file
* Replace user's home path with '...'
Part of task # ([VSC-881](https://jira.espressif.com:8443/browse/VSC-881))

## Type of change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ADD testing]

**Test Configuration**:
* ESP-IDF Version: 4.4
* OS (Windows,Linux and macOS): macOs and Windows

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

2022-09-22 11:48 UTC, brianignacio5 requested changes
I would suggest to use something different than `...` to describe that this path is indeed a user HOME directory. Maybe something like `<HOMEPATH>`.

Otherwise LGTM!

2022-09-26 09:52 UTC, brianignacio5 approved these changes

2022-09-30 14:06 UTC, AndriiFilippov commented
@radurentea hi!

Tested under:
OS - Windows 10
ESP-IDF: releasev4.4

- Run any IDF example project in VSCode(ex: blink)
- Run "Doctor Command" in the Command Palette (CTRL + SHIFT + P) / (Command + Shift + P)
- Check the esp_idf_vsc_ext.log
- Last log should contain the Doctor Command Output where all the user's path should be replaced with "..."
- Example: '/Users/<name of the user>/esp/blink' should be replaced with '/Users/<HOMEPATH>/esp/blink' 

Was able to see changes. LGTM. 
Continue testing on Linux/MacOS

```
\bin;C:<HOMEPATH>/AppData/Local/Programs/jaguar;C:<HOMEPATH>\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python38\\\\;C:<HOMEPATH>\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python38\\\\Scripts\\\\;C:<HOMEPATH>\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps;\",\"extensionVersion\":\"1.5.0\",\"language\":\"en\",\"shell\":\"C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe\",\"platform\":\"win32\",\"systemName\":\"10.0.19044\",\"vscodeVersion\":\"1.71.2\"},\"workspaceFolder\":\"c:<HOMEPATH>\\\\e\\\\esp-idf-v4.4.2\\\\examples\\\\blink\"}","timestamp":"2022-09-30T12:40:43.115Z"}
```

2022-10-03 10:07 UTC, AndriiFilippov commented
@radurentea 

Tested under: 
OS - Ubuntu 20.04 
ESP-IDF: release/v4.4

LGTM 

`\"3.8.10\"},\"systemInfo\":{\"architecture\":\"x64\",\"envPath\":\"<HOMEPATH>/.local/bin:<HOMEPATH>/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin\",\"extensionVersion\":\"1.5.0\",\"language\":\"en\",\"shell\":\"/usr/bin/bash\",\"platform\":\"linux\",\"systemName\":\"5.15.0-46-generic\",\"vscodeVersion\":\"1.71.1\"},\"workspaceFolder\":\"<HOMEPATH>/e/esp-idf-v4.4.2/examples/blink\"}","timestamp":"2022-10-03T09:58:55.225Z"}`

2022-10-03 10:47 UTC, merged