Enhance: Enable usage of white spaces in project's path
espressif/vscode-esp-idf-extension pull request #943
Opened 2023-04-18 05:36 UTC by radurentea

## Description

Enable usage of white spaces in project's path.

## Type of change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Create a project that has a white space in it. Ex: "My Project"
2. Build, Flash, Monitor it
3. Observe results.

- Expected behaviour:
With these changes, user should be able to use the VsCode extension and it's features on projects that have white spaces in their path

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Tested building, flashing and monitoring on all OS

**Test Configuration**:
* ESP-IDF Version: 5.1
* OS (Windows,Linux and macOS): Windows, Linux, macOS

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

2023-07-25 11:00 UTC, brianignacio5 requested changes
Left a few changes about code. Will test on Windows soon.

2023-07-25 12:06 UTC, radurentea commented on src/espIdf/monitor/index.ts
> +import { get } from "http";
Done, thank you!

2023-07-25 12:07 UTC, radurentea commented on src/espIdf/size/idfSizeTask.ts
> +import { get } from "http";
Done thank you!

2023-07-26 10:52 UTC, brianignacio5 commented
I did a series of tests in Windows 10.

While the current PR does indeed solve the issue of spaces in the current project path for build, flash monitor commands; it doesn't take into account the support of spaces in ESP-IDF or ESP-IDF tools which could also happen. The validation in the setup wizard was removed to validate spaces, so I think we should also support spaces in ESP-IDF, ESP-IDF tools and PATH. 

I think we should have some ESP-IDF version validation too, because spaces in ESP-IDF started to be supported from v5.0 if I'm not mistaken.

2023-07-26 11:18 UTC, radurentea commented
> While the current PR does indeed solve the issue of spaces in the current project path for build, flash monitor commands; it doesn't take into account the support of spaces in ESP-IDF or ESP-IDF tools which could also happen. The validation in the setup wizard was removed to validate spaces, so I think we should also support spaces in ESP-IDF, ESP-IDF tools and PATH.

But it does offer support for spaces in esp-idf and esp-idf tools. If esp-idf and esp-idf tools paths contain spaces, they should still work, that's how I've tested the changes for all OS.

> 
> I think we should have some ESP-IDF version validation too, because spaces in ESP-IDF started to be supported from v5.0 if I'm not mistaken.

Where should I add this validation? I was thinking to maybe add like a warning inside the UI of ESP-IDF SETUP web view for express and advanced (if user selects an esp-idf version that doesn't support white spaces) and for the Use Existing Setup (should have like a warning inside each option again that uses an esp-idf version that doesn't support white spaces)
What do you think?

2023-07-26 11:25 UTC, brianignacio5 commented
> > While the current PR does indeed solve the issue of spaces in the current project path for build, flash monitor commands; it doesn't take into account the support of spaces in ESP-IDF or ESP-IDF tools which could also happen. The validation in the setup wizard was removed to validate spaces, so I think we should also support spaces in ESP-IDF, ESP-IDF tools and PATH.
> 
> But it does offer support for spaces in esp-idf and esp-idf tools. If esp-idf and esp-idf tools paths contain spaces, they should still work, that's how I've tested the changes for all OS.
> 
> > I think we should have some ESP-IDF version validation too, because spaces in ESP-IDF started to be supported from v5.0 if I'm not mistaken.
> 
> Where should I add this validation? I was thinking to maybe add like a warning inside the UI of ESP-IDF SETUP web view for express and advanced (if user selects an esp-idf version that doesn't support white spaces) and for the Use Existing Setup (should have like a warning inside each option again that uses an esp-idf version that doesn't support white spaces) What do you think?

Yes having the warning in the Setup Wizard and adding in the readme and install tutorial a warning for all esp-idf < 5.0 should be enough. I just mentioned the version because we still have to support v4.3 and v4.4 until end of next year

2023-08-14 14:18 UTC, birdistheword96 commented
Following this intently as its a really important fix. I can't change my user-name (which has a space in) at work so I currently cannot use VS-Code extension, I have to use the power-shell and call the commands separately. Cannot wait for this fix to be pushed.

2023-08-18 08:02 UTC, brianignacio5 approved these changes
LGTM with minor comment

2023-08-18 08:02 UTC, brianignacio5 commented on src/views/setup/components/selectEspIdf.vue
> +      const match = this.selectedIdfVersion.name.match(/v(\d+(\.\d+)?(\.\d+)?)/);
Any reason why not using the version validation in the helper function in `.../store/index.ts` ?

2023-08-21 10:32 UTC, brianignacio5 approved these changes
LGTM

2023-08-24 12:35 UTC, AndriiFilippov commented
@radurentea hi! 

Tested under:
OS - Windows 10 
ESP-IDF: v5.1 

Is there any space set restrictions ? Because when I add more spaces - I can't build project via VS Code, but able to build via terminal

SV Code LOGS: 

```
*  Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B 'c:\Users\AndriiFilippov\project                  name\build' -S 'c:\Users\AndriiFilippov\project                  name' 

CMake Error: The source directory "C:/Users/AndriiFilippov/project name" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B 'c:\Users\AndriiFilippov\project                  name\build' -S 'c:\Users\AndriiFilippov\project                  name'" terminated with exit code: 1.
```


Terminal LOGS:

```
ifi_provisioning.dir/proto-c/wifi_constants.pb-c.c.obj←[883/884] Generating binary image from built executable←[Kesptool.py v4.7.dev1.obj←[K.obj←[K/src/scheme_softap.c.obj←[K
Creating esp32 image...
Merged 2 ELF sections
Successfully created esp32 image.
Generated C:/Users/AndriiFilippov/e/TEST SPACES/esp-idf-v5.1/examples/project                        name/build/project.bin
[884/884] cmd.exe /C "cd /D "C:\Users\AndriiFilippov\e\TES...es/project                        name/build/project.bin""←[Kproject.bin binary size 0x2aa60 bytes. Smallest app partition is 0x100000 bytes. 0xd55a0 bytes (83%) free.

Project build complete. To flash, run this command:
C:\Users\AndriiFilippov\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe ..\..\components\esptool_py\esptool\esptool.py -p (PORT) -b 460800 --before default_reset --after hard_reset --chip esp32  write_flash --flash_mode dio --flash_size 2MB --flash_freq 40m 0x1000 build\bootloader\bootloader.bin 0x8000 build\partition_table\partition-table.bin 0x10000 build\project.bin
or run 'idf.py -p (PORT) flash'
```

2023-08-25 08:23 UTC, AndriiFilippov commented
@radurentea 

Also whenever I create project with spaces I do have this messages in console: 

```
[proc] Executing command: cmake --version
[proc] The command: cmake --version failed with error: Error: spawn cmake ENOENT
[proc] Executing command: cmake -E capabilities
[proc] The command: cmake -E capabilities failed with error: Error: spawn cmake ENOENT
[variant] Loaded new set of variants
[kit] Successfully loaded 1 kits from C:\Users\AndriiFilippov\AppData\Local\CMakeTools\cmake-tools-kits.json
[main] Configuring project: project is name 
[main] Configuring project: project is name
```

2023-08-28 16:14 UTC, radurentea commented
Hi @AndriiFilippov ,

Can you re-test again for both of the issues you've found previously?

2023-08-30 16:18 UTC, AndriiFilippov commented
> @radurentea
> 
> Also whenever I create project with spaces I do have this messages in console:
> 
> ```
> [proc] Executing command: cmake --version
> [proc] The command: cmake --version failed with error: Error: spawn cmake ENOENT
> [proc] Executing command: cmake -E capabilities
> [proc] The command: cmake -E capabilities failed with error: Error: spawn cmake ENOENT
> [variant] Loaded new set of variants
> [kit] Successfully loaded 1 kits from C:\Users\AndriiFilippov\AppData\Local\CMakeTools\cmake-tools-kits.json
> [main] Configuring project: project is name 
> [main] Configuring project: project is name
> ```
> 
> Do you know what is it ?

@radurentea , This one still persist, but I think we can create separate ticket for this one ? what do you think ? 

Tested on Linux as well, everything works fine, but on the Extension Configuration finish page I do see this info message: 
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/7916de87-bee7-45cd-84ab-3ac3e2001c5c)


But, this command does not work with spaces in the PATH : 
![image](https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/9618dd7a-4059-466b-9898-cb37f59f8999)


I think we should do something with this one.

2023-08-31 09:30 UTC, radurentea commented
@AndriiFilippov 
Made the modifications for the linux command. You can re-test it.

Regarding this one:
```
[proc] Executing command: cmake --version
[proc] The command: cmake --version failed with error: Error: spawn cmake ENOENT
[proc] Executing command: cmake -E capabilities
[proc] The command: cmake -E capabilities failed with error: Error: spawn cmake ENOENT
[variant] Loaded new set of variants
[kit] Successfully loaded 1 kits from C:\Users\AndriiFilippov\AppData\Local\CMakeTools\cmake-tools-kits.json
[main] Configuring project: project is name 
[main] Configuring project: project is name
```
it doesn't seem to be an issue with current PR, I was not able to reproduce it.

2023-09-01 12:00 UTC, AndriiFilippov commented
@radurentea 
<img width="1680" alt="Screenshot 2023-09-01 at 10 09 09" src="https://github.com/espressif/vscode-esp-idf-extension/assets/69584713/1e317343-ba96-4ad0-88ec-f6ae47f318cb">

Also can't build on MacOS. 
Please, check


``` *  Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B="/Users/andrii/project-name            s/build" -S="/Users/andrii/project-name            s" 

zsh:1: command not found: cmake

 *  The terminal process "/bin/zsh '-l', '-c', 'cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B="/Users/andrii/project-name            s/build" -S="/Users/andrii/project-name            s"'" failed to launch (exit code: 127). 
```

2024-01-31 04:21 UTC, nrgbistro commented
Unfortunately I don't have the time or skill to contribute but I would love to see this merged in the next release!

For context, I put both my `IDF_PATH` and `IDF_TOOLS_PATH` in locations that contain no spaces. However, I still cannot build my project that is stored in the following path: `C:\Users\username\OneDrive - xxxx University\Classes\2024 Spring\IOT\Labs\Lab 1`

Here's the build error:

```
Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B c:\Users\username\OneDrive - xxxx University\Classes\2024 Spring\IOT\Labs\Lab 1\build -S c:\Users\username\OneDrive - xxxx University\Classes\2024 Spring\IOT\Labs\Lab 1 

CMake Warning:
  Ignoring extra path from command line:

   "1"


CMake Error: Unknown argument -
CMake Error: Run 'cmake --help' for all supported options.
```

I've tried a few combinations of paths and can't seem to get consistent results unless there are no spaces present in the path, which makes using OneDrive very difficult. I'm using v1.7.0 of this extension.

2024-04-04 13:08 UTC, closed without merging

2024-04-04 13:08 UTC, radurentea commented
New PR for adding support for white spaces can be found here:
https://github.com/espressif/vscode-esp-idf-extension/pull/1159